'''Guess the random number generated by the computer.'''


import random           #Import Random
guess = 0               #Declare global variable




def guess_choice():        #Guess choice function. Called repeatedly if choices are incorrect or not valid.
    global guess            #Global variable guess
    user_guess = input()
    try:
        guess = int(user_guess)         #Checks that the input is an integer
    except ValueError:
        print ('Sorry, that is not a number. Please choose a value between 1 and 10.')
        guess_choice()            #Runs the function from the start until an appropriate response is given.




def num_guess():            #Guessing function
    global guess
    num = random.randint(1,10)      #Random number that will be guessed
    print ('Try to guess the number that is between 1 and 10.')

    guess_choice()              #Runs the guess input function listed above.

    while guess < 1 or guess > 10:          #Establishes the range that guesses are allowed within
        print ('Sorry, you must guess a number between 1 and 10. Guess again')
        guess_choice()
    else:
        while guess != num:             #Guess too high
            if guess > num:
                print('You have guessed too high. Guess again.')
                guess_choice()
            elif guess < num:           #Guess too low
                print ('You have guessed too low. Guess again.')
                guess_choice()
        else:
            print ('You have guessed the correct number. The secret number is %d.' % num)

num_guess()